// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvstytZnTnEgvcDNEgbHQZ05RSRWIMVxw',
    appId: '1:298034787315:web:19b17458f589557f0f9886',
    messagingSenderId: '298034787315',
    projectId: 'hostelappauth',
    authDomain: 'hostelappauth.firebaseapp.com',
    storageBucket: 'hostelappauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQJCN_vyK7q7L_LCAkUYAnz2MjsxY5j3c',
    appId: '1:298034787315:android:ada220e4798ad4710f9886',
    messagingSenderId: '298034787315',
    projectId: 'hostelappauth',
    storageBucket: 'hostelappauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhAEGcmlOuhy77pxYgSWWG040w6oeE7Wo',
    appId: '1:298034787315:ios:0d5f5f2dbf8a1a840f9886',
    messagingSenderId: '298034787315',
    projectId: 'hostelappauth',
    storageBucket: 'hostelappauth.appspot.com',
    iosBundleId: 'com.example.hostelAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhAEGcmlOuhy77pxYgSWWG040w6oeE7Wo',
    appId: '1:298034787315:ios:0d5f5f2dbf8a1a840f9886',
    messagingSenderId: '298034787315',
    projectId: 'hostelappauth',
    storageBucket: 'hostelappauth.appspot.com',
    iosBundleId: 'com.example.hostelAppMobile',
  );
}
